var app = angular.module('autogeneratedForm')
    .directive('bpComplex', function() {
        return {
            restrict: 'E',
            templateUrl: 'templates/complex.html'
        };
    })
    .directive('bpComplexMultiple', function() {
        return {
            restrict: 'E',
            templateUrl: 'templates/complexMultiple.html'
        };
    })
    .directive('bpFiles', function() {
        return {
            restrict: 'E',
            templateUrl: 'templates/files.html'
        };
    })
    .directive('bpMultiple', function() {
        return {
            restrict: 'E',
            templateUrl: 'templates/multiple.html'
        };
    })
    .directive('bpSimple', function() {
        return {
            restrict: 'E',
            templateUrl: 'templates/simple.html'
        };
    })
;
