(function () {
  'use strict';
  angular.module('autogeneratedForm').factory('contractSrvc', ['$http', function($http) {

    function appendTransform(defaults, transform) {

      // We can't guarantee that the default transformation is an array
      defaults = angular.isArray(defaults) ? defaults : [defaults];

      // Append the new transformation to the defaults
      return defaults.concat(transform);
    }


    return {
      fetchContract: function (id) {
        // fetch contract from server
        return $http({
          url: '../API/bpm/process/' + id + '/contract',
          method: 'GET'
        });
      },
      startProcess: function(id, dataToSend) {
        // submit data to start process on server
        return $http({
          url: '../API/bpm/process/' + id + '/instantiation',
          method: 'POST',
          data: dataToSend,
          transformRequest: appendTransform($http.defaults.transformRequest, function(value, headers) {
            console.log('Request:', value);
            return value;
          })
        });
      }
    };
  }]);
})();
